name: Bug report
description: Create a bug report about a reproducible problem.
labels: bug
body:
- type: checkboxes
  id: searched-discussions
  attributes:
    label: Please Confirm
    options:
      - label: I have reviewed the **[MIDIKit Documentation](https://orchetect.github.io/MIDIKit)** which contains descriptive guides and extensive API reference
        required: true
      - label: I have searched **[Issues](https://github.com/orchetect/MIDIKit/issues?q=is%3Aissue)** and **[Discussions](https://github.com/orchetect/MIDIKit/discussions)** to see if the same question has already been asked
        required: true
- type: dropdown
  id: operating-system
  attributes:
    label: "macOS Version(s) Used to Build"
    description: The operating system version being used to build (not the target runtime OS version).
    multiple: true
    options:
      - "macOS 26.x Tahoe"
      - "macOS 15.x Sequoia"
      - "macOS 14.x Sonoma"
      - "macOS 13.x Ventura"
      - "Other"
  validations:
    required: true
- type: dropdown
  id: xcode-version
  attributes:
    label: "Xcode Version(s)"
    multiple: true
    options:
      - "Xcode 26.x"
      - "Xcode 16.x"
      - "Xcode 15.x"
      - "Other"
  validations:
    required: true
- type: textarea
  id: bug-description
  attributes:
    label: Description
    description: "A clear description of the bug, steps to reproduce, console logs, screen shots, etc."
  validations:
    required: true
